[project]
name = "diffusion-model-emoji"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.5.0",
    "denoising-diffusion-pytorch>=2.2.6",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
